language: node_js
node_js:
- '0.10'
before_install:
  - npm install npm -g
before_deploy:
  - npm install ws browserify coffeeify
  - mkdir -p deploy/meshblu-echo/latest
  - mkdir -p deploy/meshblu-echo/$TRAVIS_TAG
  - node_modules/.bin/browserify -t coffeeify -s Connector connector.js > deploy/meshblu-echo/latest/meshblu-echo.js
  - gzip deploy/meshblu-echo/latest/meshblu-echo.js
  - mv deploy/meshblu-echo/latest/meshblu-echo.js.gz deploy/meshblu-echo/latest/meshblu-echo.js
  - cp deploy/meshblu-echo/latest/meshblu-echo.js deploy/meshblu-echo/$TRAVIS_TAG/meshblu-echo.js
deploy:
  - provider: s3
    region: us-west-2
    skip_cleanup: true
    detect_encoding: true
    access_key_id: AKIAJH2D5IPIRHYJT5IA
    secret_access_key:
      secure: "GgbGNxatwHIuhASVfbKeNz87Pa2Gci5Epmbje/qX9rCeJCoMX5abodep1YKTReRcAgOM42vCRczw3/RKn3KylgqGSaRk5PmKgpZtoGJ/3p8PE7SdeCeDMciti+ZpbUZt4rXy/LBnNA116twiLsswiHpU5ZiE+htDF17jcOm2rys="
    bucket: octoblu-cdn
    local-dir: deploy
    upload-dir: js
    on:
      tags: true
      all_branches: true
  - provider: npm
    skip_cleanup: true
    clean_up: false
    email: serveradmin@octoblu.com
    api_key:
      secure: "fp9SXsx1eVFbXbkQCtgBhxvd1ryGEO/+Laa4p1GeZobSuF+6/xNFQogvb6XONJHYb3j+d6zsz8/rBX9hWVN1CG8RNluNan2asfV+eaU6aGxyzDjQj6o7DyTWPwyeK4OyzzllIkTyqiM0G6WEtt+SMZWnnR8Tp2AQQ7HnUKIy9kQ="
    on:
      tags: true
      all_branches: true
